name: Run Build

on:
 pull_request:
  branches: [develop,main]

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   - name : checkout
     uses: actions/checkout@v4.2.1

   - name: Setup Java JDK
     uses: actions/setup-java@v4.4.0
     with:
      java-version: 21
      distribution: temurin

   - name: Grant execute permissions for gradlew
     run: chmod +x gradlew

   - name: Install yarn dependencies
     run: yarn install 

   - name: Run unit tests
     run: ./gradlew test

   - name: Assemble Release Bundle
     run: |
        cd android
        ./gradlew bundleRelease
